using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CascadePOCHomePage.Helpers
{
    class IconFontAwesome
	// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
	// If you change the class to 'public' in order to use it outside its assembly
	//  you should also change the fields from 'const' to 'public static readonly'
	{
		public const string Nonmarkingreturn = "\u000d";
		public const string Space = "\u0020";
		public const string Eth = "\u00f0";
		public const string Lslash = "\u0141";
		public const string Icon1 = "\u0142";
		public const string Scaron = "\u0160";
		public const string Icon2 = "\u0161";
		public const string Yacute = "\u00dd";
		public const string Icon3 = "\u00fd";
		public const string HT = "\u0009";
		public const string LF = "\u000a";
		public const string Thorn = "\u00de";
		public const string Icon4 = "\u00fe";
		public const string Zcaron = "\u017d";
		public const string Icon5 = "\u017e";
		public const string DLE = "\u0010";
		public const string DC1 = "\u0011";
		public const string DC2 = "\u0012";
		public const string DC3 = "\u0013";
		public const string DC4 = "\u0014";
		public const string Onehalf = "\u00bd";
		public const string Onequarter = "\u00bc";
		public const string Onesuperior = "\u00b9";
		public const string Threequarters = "\u00be";
		public const string Threesuperior = "\u00b3";
		public const string Twosuperior = "\u00b2";
		public const string Brokenbar = "\u00a6";
		public const string Minus = "\u2212";
		public const string Multiply = "\u00d7";
		public const string RS = "\u001e";
		public const string Numbersign = "\u0023";
		public const string Parenleft = "\u0028";
		public const string Parenright = "\u0029";
		public const string Asterisk = "\u002a";
		public const string Plus = "\u002b";
		public const string Zero = "\u0030";
		public const string Three = "\u0033";
		public const string Less = "\u003c";
		public const string Greater = "\u003e";
		public const string Question = "\u003f";
		public const string J = "\u004a";
		public const string K = "\u004b";
		public const string M = "\u004d";
		public const string P = "\u0050";
		public const string S = "\u0053";
		public const string U = "\u0055";
		public const string W = "\u0057";
		public const string Y = "\u0059";
		public const string Backslash = "\u005c";
		public const string j = "\u006a";
		public const string k = "\u006b";
		public const string l = "\u006c";
		public const string m = "\u006d";
		public const string o = "\u006f";
		public const string p = "\u0070";
		public const string q = "\u0071";
		public const string s = "\u0073";
		public const string v = "\u0076";
		public const string w = "\u0077";
		public const string x = "\u0078";
		public const string Icon6 = "\u00d0";
	}
}
